---
- name: RestartInstanaAgent
  hosts: all
  tasks:
    - name: Execute shell
      ansible.builtin.shell: |
        sudo systemctl restart --quiet instana-agent
        echo "Instana Agent restarted via systemd."
      register: shell_output

    - name: Show output
      ansible.builtin.debug:
        var: shell_output.stdout
