---
- name: RestartInstanaAgent
  hosts: all
  tasks:
    - name: Execute script.sh
      ansible.builtin.shell: /bin/sh /opt/scripts/script.sh
      register: script_output

    - name: Show output
      ansible.builtin.debug:
        var: script_output.stdout
