---
- name: RestartInstanaAgent
  hosts: all
  tasks:
    - name: restart Instana-Agent
      ansible.builtin.service:
        name: instana-agent
        state: restarted        
      become: true
      
    
